docs: smart-contracts documentation
NexusMutual/smart-contracts pull request #1295
Opened 2024-11-29 13:45 UTC by rackstar

## Paste the latest smart-contract docs to be reviewed under the line

---------------------------------------------------------------------------------------------------

2024-11-29 13:50 UTC, rackstar commented
## Tasks

- [x] Ramm.sol
- [x] StakingPool.sol
- [x] Pool.sol
- [x] Cover.sol
- [x] StakingProducts.sol
- [ ] StakingFactory.sol @rackstar 
- [ ] Assessment.sol @MilGard91

2025-02-27 15:06 UTC, MilGard91 requested changes

2025-02-27 15:06 UTC, MilGard91 commented on docs/diagrams/contracts/token.md
> +
Add only members can acquire NXM Token

2025-02-28 10:00 UTC, rackstar commented on docs/diagrams/contracts/cover.md
> +3. Cover purchases require product validation
dropped. it was leftover from previous draft

2025-02-28 10:19 UTC, rackstar commented on docs/diagrams/contracts/governance.md
> +4. **Withdraw Membership**
I based on our contract dir grouping:

```
governance
├── Governance.sol
├── MemberRoles.sol
├── NXMaster.sol
├── ProposalCategory.sol
└── VotePower.sol
```

hence I named it governance. maybe **Governance & Membership Contracts**?

2025-02-28 10:36 UTC, rackstar commented on docs/diagrams/contracts/token.md
> +
added

2025-02-28 10:37 UTC, rackstar commented on docs/diagrams/contracts/claims-assessment.md
> +- Claims must be submitted within the grace period after cover expiry
changed to:
```
- Claims can be submitted before the grace period ends (cover expiry + grace period days)
```

2025-02-28 10:38 UTC, rackstar commented on docs/diagrams/contracts/cover.md
> +1. Members can purchase cover by minting Cover NFTs
changed to:
```
1. Members receive a Cover NFT as proof when purchasing cover
```

2025-02-28 10:38 UTC, rackstar commented on docs/diagrams/contracts/cover.md
> +2. AB Members manage product configurations
changed to:
```
2. AB Members manage products
```

2025-02-28 10:39 UTC, rackstar commented on docs/diagrams/contracts/token.md
> +
changed to, i've added something for the allowances too:
```
1. Only members can hold, receive, or transfer NXM tokens
2. Members can manage token allowances for approved addresses
```

2025-02-28 11:42 UTC, MilGard91 commented on docs/diagrams/contracts/governance.md
> +4. **Withdraw Membership**
Sounds good

2025-03-10 15:09 UTC, merged