Feature/router views
NexusMutual/smart-contracts pull request #186
Opened 2022-02-23 12:05 UTC by danoctavian

2022-03-09 14:31 UTC, roxdanila commented on contracts/modules/v2/StakingPool.sol
> +import "hardhat/console.sol";
remove

2022-03-09 14:31 UTC, roxdanila commented on contracts/modules/cover/Cover.sol
> +import "hardhat/console.sol";
remove

2022-03-09 14:45 UTC, roxdanila approved these changes

2022-04-05 11:00 UTC, shark0der requested changes
- Remove capacity params from staking pool
- Use an absolute time instead of a cover period

2022-04-14 07:17 UTC, horodnicdragos approved these changes

2022-05-05 07:34 UTC, merged