Fix claim assessment timelock
NexusMutual/smart-contracts pull request #258
Opened 2022-08-02 17:03 UTC by shark0der

2022-08-03 08:14 UTC, danoctavian commented
worth having a unit/integration test for this new logic

2022-08-03 11:04 UTC, danoctavian commented on contracts/modules/claims/ClaimsReward.sol
> +        if (currentExpiration.sub(reduction) < minExpiration) {
so this means that you will always have to wait at least min lock time correct?

There's no way to get this lock time down to block.timestamp

2022-08-03 11:49 UTC, danoctavian commented on contracts/modules/claims/ClaimsReward.sol
> +          reduction = currentExpiration - minExpiration;
use .sub here

2022-08-04 08:58 UTC, roxdanila requested changes
Fix looks good.
Please add a test as discussed offline and then loop in Iosiro for the final review.

2022-08-08 11:22 UTC, roxdanila approved these changes

2022-08-08 11:37 UTC, merged