Chore: Upgrade hardhat to v2.11
NexusMutual/smart-contracts pull request #373
Opened 2022-09-09 10:06 UTC by kyledewy

## Context
closes #359 

## Changes proposed in this pull request
This PR upgrades hardhat and solidity-coverage to the latest releases. This PR also changed the `typechain` dependency to the hardhat native `@typechain/hardhat`, as well as update `@typechain/truffle-v5`. 

## Test plan
No further tests were added

2022-09-09 10:53 UTC, kyledewy commented on test/unit/CowOperator/placeOrder.js
> +    const rcpOrder = rcp.events[2].args.order.slice(0, 12);
I don't love this solution. It seems with the upgrade the event receipt has duplicate values  and the BigNumber type is different from parseEther(). Open to suggestions for a cleaner approach.

2022-09-13 08:29 UTC, shark0der requested changes
Make sure typechain works, remove custom typechain task, switch to config

2022-09-13 11:07 UTC, shark0der commented on hardhat.config.js/index.js
> +    outDir: 'src/types',
`outDir` should be `'types'` (drop the `src/`)

2022-09-13 11:10 UTC, shark0der commented on hardhat.config.js/index.js
> +    dontOverrideCompile: true, // defaults to false
- `outDir` should be `'types'` (drop the `src/`)
- we currently don't have external artifacts, remove that line. if we want it - let's do another PR as it's a new feature that's out of scope for this one

2022-09-13 16:45 UTC, shark0der approved these changes

2022-09-13 16:45 UTC, merged