add initialize function to Cover
NexusMutual/smart-contracts pull request #378
Opened 2022-09-14 14:26 UTC by danoctavian

2022-09-26 10:18 UTC, shark0der commented on test/unit/Cover/initialize.js
> +const { bnEqual } = require('../utils').helpers;
:warning: Please stop using oz test helpers and bnEqual for v2!  
- `bnEqual` raises a warning with instructions on what to use instead.
- `expectRevert` should be replaced with chai assertions (`to.be.reverted` thing)

2022-09-26 10:18 UTC, shark0der requested changes
The actual implementation looks good. Please switch from oz/bnEqual in the new test with suggested tools.

2022-09-26 20:11 UTC, danoctavian commented
@shark0der  addressed as requested

2022-09-27 06:59 UTC, kyledewy approved these changes

2022-09-27 12:17 UTC, shark0der approved these changes

2022-09-27 12:18 UTC, merged