Test/ Add constructor and initialize assessment tests
NexusMutual/smart-contracts pull request #443
Opened 2022-10-25 12:18 UTC by paterson1

## Context

Closes #432 

## Changes proposed in this pull request

Adds new unit tests for the constructor and initialize. Implemented the list of test cases from the issue. `nxm` was changed to `public` to be able to fetch it for testing, and logic to test whitelisting was added to `ASMockTokenController`. 

## Test plan

New tests were added in `test/unit/Assessment/initialize.js` and `test/unit/Assessment/constructor.js`

## Checklist

- [x] Rebased the base branch
- [x] Attached corresponding Github issue
- [x] Prefixed the name with the type of change (i.e. feat, chore, test)
- [x] Performed a self-review of my own code
- [x] Followed the style guidelines of this project
- [ ] Made corresponding changes to the documentation
- [x] Didn't generate new warnings
- [x] Didn't generate failures on existing tests
- [x] Added tests that prove my fix is effective or that my feature works

## Review

When reviewing a PR, please indicate intention in comments using the following emojis:
* :cake: = Nice to have but not essential.
* :bulb: = Suggestion or a comment based on personal opinion
* :hammer: = I believe this should be changed.
* :thinking: = I don’t understand something, do you mind giving me more context?
* :rocket: = Feedback

2022-10-25 13:52 UTC, danoctavian commented
@paterson1  conflicts with base branch - needs a rebase

2022-10-25 14:52 UTC, danoctavian commented on test/unit/Assessment/initialize.js
> +    expect(afterInitializeConfig.minVotingPeriodInDays).to.be.to.be.equals(3);
to.be.to.be repeated

interestingly it works.

2022-10-25 14:53 UTC, danoctavian commented on test/unit/Assessment/initialize.js
> +    expect(preInitializeConfig.minVotingPeriodInDays).to.be.equals(0);
write `to.be.equal` (singular) not `equals`

2022-10-25 15:02 UTC, danoctavian commented on test/unit/Assessment/castVotes.js
>        await expect(tx).to.emit(assessment, 'VoteCast').withArgs(user2.address, 1, parseEther('1000'), false);
these tests belong to another PR right?

2022-10-25 15:04 UTC, danoctavian commented on contracts/mocks/Assessment/ASMockTokenController.sol
> +  function removeFromWhitelist(address _member) public {
this doesn't seem to be used.

No test for removal.

removeFromWhitelist

2022-10-25 15:06 UTC, danoctavian requested changes
Some changes necessary

2022-10-26 00:28 UTC, danoctavian approved these changes
LGTM

2022-10-26 08:24 UTC, roxdanila approved these changes

2022-10-26 08:24 UTC, merged