Feature/lock time 30
NexusMutual/smart-contracts pull request #50
Opened 2021-01-06 12:59 UTC by danoctavian

2021-01-06 16:05 UTC, roxdanila requested changes

2021-01-06 16:07 UTC, roxdanila commented
@danoctavian check out the failing test, looks related

2021-01-06 19:50 UTC, danoctavian commented on contracts/modules/staking/PooledStaking.sol
> +
with check:
{ gas: 188371 }
without check:
{ gas: 187426 }

~0.5% gas increase

2021-01-07 04:44 UTC, danoctavian commented
locking both requestUnstake and _processFirstUnstakeRequest during the migration because it can alter the structure of the list and disrupt the iteration (low probability though)

2021-01-11 09:22 UTC, shark0der commented on contracts/modules/staking/PooledStaking.sol
> +  uint public REWARD_ROUNDS_START = 1600074000;
These are misleading. We're using a proxy so these will be unset in a proxy.

2021-01-11 09:36 UTC, danoctavian commented on contracts/modules/staking/PooledStaking.sol
> +      unstakeRequest.unstakeAt = unstakeRequest.unstakeAt - 60 days;
should use SafeMath here

2021-01-11 17:45 UTC, roxdanila commented on contracts/modules/staking/PooledStaking.sol
> +    require(migrationStatus == 0, 'PooledStaking: Migration finished');
nit: make it explicit what migration this is

2021-01-11 17:55 UTC, roxdanila commented on test/fork/migrateTo30DaysLockTime.js
> +    const REWARD_ROUNDS_START = await ps.REWARD_ROUNDS_START();
don't need these

2021-01-11 17:56 UTC, roxdanila commented on test/fork/migrateTo30DaysLockTime.js
> +    assert.equal(NEW_REWARD_ROUNDS_START.toString(), REWARD_ROUNDS_START.toString());
same as above

2021-01-11 18:00 UTC, roxdanila commented on test/fork/migrateTo30DaysLockTime.js
> +      assert.equal(before.amount.toString(), before.amount.toString());
uhm :)

2021-01-11 18:01 UTC, roxdanila approved these changes
minor comments, looks good overall

2021-01-12 14:59 UTC, danoctavian commented on test/fork/migrateTo30DaysLockTime.js
> +      assert.equal(before.amount.toString(), before.amount.toString());
oops

2021-01-12 15:01 UTC, cleanunicorn commented on test/fork/migrateTo30DaysLockTime.js
> +const addNewInternalContractCategoryId = 34;
These 2 variables don't seem to be used anywhere.

2021-01-12 16:22 UTC, merged