Bug/initial deposit revert
NexusMutual/smart-contracts pull request #501
Opened 2022-11-17 10:11 UTC by MilGard91

## Context

BUG: When there is a deposit amount on the creation of the new staking pool, the msg.sender was the Cover Contract since the method was called from it. Revert happens since there is no balance on the contract itself.

Issue: https://github.com/NexusMutual/smart-contracts/issues/315

## Changes proposed in this pull request

Before transfer check the sender, if it is Cover Contract then do the transfer from the manager.

## Test plan

Test expanded with integration tests for creating staking pools with initial deposits. One for the private stake, and one for the public. Tests also include staking of the manager and one additional staker after pool creation.

## Checklist

- [x] Rebased the base branch
- [x] Attached corresponding Github issue
- [x] Prefixed the name with the type of change (i.e. feat, chore, test)
- [x] Performed a self-review of my own code
- [x] Followed the style guidelines of this project
- [ ] Made corresponding changes to the documentation
- [x] Didn't generate new warnings
- [x] Didn't generate failures on existing tests
- [x] Added tests that prove my fix is effective or that my feature works

## Review

When reviewing a PR, please indicate intention in comments using the following emojis:
* :cake: = Nice to have but not essential.
* :bulb: = Suggestion or a comment based on personal opinion
* :hammer: = I believe this should be changed.
* :thinking: = I don’t understand something, do you mind giving me more context?
* :rocket: = Feedback

2022-11-17 23:21 UTC, danoctavian commented on test/integration/Cover/stakingPools.js
> +const { ethers } = require('hardhat');
name the file 
createStakingPool.js

that's what is being tested

2022-11-17 23:22 UTC, danoctavian commented on test/integration/Cover/stakingPools.js
> +describe('Creating Staking Pools with funds', function () {
describe('createStakingPool')

2022-11-17 23:22 UTC, danoctavian commented on test/integration/Cover/stakingPools.js
> +    const managerNXMBalance0 = await tk.balanceOf(manager.address);
managerNXMBalanceBefore

2022-11-17 23:22 UTC, danoctavian commented on test/integration/Cover/stakingPools.js
> +    const tokenControllerBalance0 = await tk.balanceOf(tc.address);
tokenControllerBalanceBefore

2022-11-17 23:23 UTC, danoctavian commented on test/integration/Cover/stakingPools.js
> +    const managerNXMBalance1 = await tk.balanceOf(manager.address);
managerNXMBalanceAfter

2022-11-17 23:23 UTC, danoctavian commented on test/integration/Cover/stakingPools.js
> +    const tokenControllerBalance1 = await tk.balanceOf(tc.address);
tokenControllerBalanceAfter

2022-11-17 23:24 UTC, danoctavian commented on test/integration/Cover/stakingPools.js
> +    const managerStakingPoolNFTBalance0 = await stakingPool.balanceOf(manager.address);
managerStakingPoolNFTBalanceBefore

2022-11-17 23:25 UTC, danoctavian commented on test/integration/Cover/stakingPools.js
> +    const managerStakingPoolNFTBalance1 = await stakingPool.balanceOf(manager.address);
managerStakingPoolNFTBalanceAfter

2022-11-17 23:27 UTC, danoctavian commented on test/integration/Cover/stakingPools.js
> +    assert.equal(managerNXMBalance2.toString(), managerNXMBalance1.sub(deposit).toString());
you saw the pattern use Before/After in naming

2022-11-17 23:29 UTC, danoctavian commented on test/integration/Cover/stakingPools.js
> +    const txResult = await tx.wait();
afaik this is tx.wait is redundant

2022-11-17 23:30 UTC, danoctavian commented on test/integration/Cover/stakingPools.js
> +    assert.equal(managerNXMBalance1.toString(), managerNXMBalance0.sub(deposit).toString());
don't do this toString() conversion

```    expect(ethBalanceAfter).to.be.equal(ethBalanceBefore.add(segment.amount));``` 

use this syntax, should work

2022-11-17 23:30 UTC, danoctavian commented on test/integration/Cover/stakingPools.js
> +    assert.equal(managerNXMBalance1.toString(), managerNXMBalance0.sub(deposit).toString());
everywhere

2022-11-17 23:33 UTC, danoctavian commented on test/integration/Cover/stakingPools.js
> +  it('should create a public staking pool', async function () {
should create a public staking pool with an initial deposit

2022-11-17 23:33 UTC, danoctavian commented on test/integration/Cover/stakingPools.js
> +  it('should create a private staking pool', async function () {
should create a private staking pool with an initial deposit

2022-11-18 11:07 UTC, shark0der commented on contracts/modules/token/NXMToken.sol
> +    require(value <= _balances[from], "Insufficient funds to allow transfer");
The NXMToken contract is immutable and we're "stuck" with it as it is, hence we don't change the code nor compiler version for it. The deps are also copied/frozen.

2022-11-18 11:10 UTC, shark0der commented on test/integration/Cover/createStakingPool.js
> +const { expectRevert } = require('@openzeppelin/test-helpers');
We're switching from oz test helpers to waffle/chai. Remove this import

2022-11-18 11:12 UTC, shark0der commented on test/integration/Cover/createStakingPool.js
> +  });
```
await expect(stakingPool.connect(staker).depositTo([
        {
          amount: deposit,
          trancheId,
          tokenId: 0, // new position
          destination: AddressZero,
        },
      ])).to.be.revertedWith('StakingPool: The pool is private');
```

2022-11-18 11:46 UTC, shark0der commented on test/integration/Cover/createStakingPool.js
> +    const stakingPoolAddress = await cover.stakingPool(stakingPoolCountAfter - 1);
I'm expecting `stakingPoolCountAfter` to be a BigNumber, use `.sub` instead of  `-`.

2022-11-18 11:51 UTC, shark0der requested changes
Left my comments on the code :)

2022-11-22 08:25 UTC, roxdanila approved these changes

2022-11-22 08:39 UTC, shark0der approved these changes

2022-11-22 09:01 UTC, merged