Feature/masterawarev2 normalization
NexusMutual/smart-contracts pull request #502
Opened 2022-11-17 12:01 UTC by danoctavian

## Context

Include relevant motivation and context. A link to the issue is enough if it contains all the relevant 
information.

## Changes proposed in this pull request

Include a summary of the change.

## Test plan

Please describe the tests cases that you ran to verify your changes. Add further instructions on 
how to run them if needed (i.e. migration / deployment scripts, env vars, etc).

## Checklist

- [ ] Rebased the base branch
- [ ] Attached corresponding Github issue
- [ ] Prefixed the name with the type of change (i.e. feat, chore, test)
- [ ] Performed a self-review of my own code
- [ ] Followed the style guidelines of this project
- [ ] Made corresponding changes to the documentation
- [ ] Didn't generate new warnings
- [ ] Didn't generate failures on existing tests
- [ ] Added tests that prove my fix is effective or that my feature works

## Review

When reviewing a PR, please indicate intention in comments using the following emojis:
* :cake: = Nice to have but not essential.
* :bulb: = Suggestion or a comment based on personal opinion
* :hammer: = I believe this should be changed.
* :thinking: = I don’t understand something, do you mind giving me more context?
* :rocket: = Feedback

2022-11-21 11:21 UTC, kyledewy commented on contracts/modules/governance/MemberRoles.sol
> +    cover().transferCovers(msg.sender, newAddress, coverIds);
`cover()` is called twice here. i think you meant to use the `_cover` variable instead?

2022-11-21 12:35 UTC, kyledewy commented on contracts/interfaces/IMasterAwareV2.sol
> +    AS, // Assessment.sol
[TK, PS, GV] are missing comments for which contract they reference.

2022-11-21 12:54 UTC, kyledewy approved these changes
Left a couple minor comments, but otherwise LGTM :+1:

2022-11-22 09:39 UTC, shark0der requested changes
Let's make an effort to get rid of `MasterAware.sol`

2022-11-25 00:12 UTC, danoctavian commented
Removed MasterAware from all except LegacyGateway.sol

As discussed with @roxdanila  we'll postpone messing with that contract until we clarify the biz requirements around what we need to support there.

Then we'll cleanup the MasterAware as well.

2022-11-25 14:24 UTC, shark0der commented on contracts/modules/legacy/LegacyPooledStaking.sol
> +  ITokenController public _unused0;
`token` and `initialized` were removed - let's leave a comment of what happens with the storage layout here as it's not obvious why this is OK

2022-11-27 23:53 UTC, danoctavian commented on contracts/modules/capital/Pool.sol
> +    internalContracts[uint(ID.MR)] = master.getLatestAddress("MR");
Yes. 

Any MasterAwareV2 contract is using it:

https://github.com/NexusMutual/smart-contracts/blob/3bced02d04b378ed8e70deaadd1ef33a2112fb39/contracts/abstract/MasterAwareV2.sol#L17

2022-11-29 08:47 UTC, shark0der approved these changes

2022-11-29 09:26 UTC, merged