test/withdraw unit tests
NexusMutual/smart-contracts pull request #529
Opened 2022-11-28 23:35 UTC by paterson1

## Context

Closes #491 

## Changes proposed in this pull request

Added `Withdraw` event to `StakingPool` contract and `withdrawNXMStakeAndRewards` method to `TokenControllerMock`. 

To consider: Calling `withdraw` stake doesn't revert even when one of the tranches is not expired (that test is passing). and is possible to withdraw on behalf of another user, but I am not sure if that is a desirable feature.

## Test plan

Added unit tests to `StakingPool/withdraw.js`.

## Checklist

- [ ] Rebased the base branch
- [ ] Attached corresponding Github issue
- [ ] Prefixed the name with the type of change (i.e. feat, chore, test)
- [ ] Performed a self-review of my own code
- [ ] Followed the style guidelines of this project
- [ ] Made corresponding changes to the documentation
- [ ] Didn't generate new warnings
- [ ] Didn't generate failures on existing tests
- [ ] Added tests that prove my fix is effective or that my feature works

## Review

When reviewing a PR, please indicate intention in comments using the following emojis:
* :cake: = Nice to have but not essential.
* :bulb: = Suggestion or a comment based on personal opinion
* :hammer: = I believe this should be changed.
* :thinking: = I don’t understand something, do you mind giving me more context?
* :rocket: = Feedback

2022-12-02 13:23 UTC, paterson1 commented on test/unit/StakingPool/withdraw.js
> +      .withArgs(user.address, depositNftId, trancheIds[2], stakes[2], rewards[2]);
This should have index 0, I'm still debugging why is not the same as the emitted args.

2022-12-21 20:19 UTC, patitonar commented
> Pushed a failed test.

While reviewing this test I noticed that the total amount of minted rewards was not being distributed to the users and manager, there was a small amount that remained locked in the contract. After debugging I found that the cause of this small amount was a precision loss in the calculation of `accNxmPerRewardsShare`. 

As it is calculated with the following formula `elapsed * _rewardPerSecond / _rewardsSharesSupply` there were a lot of decimals truncated causing the accumulated value to be less than the actual amount to distribute. The solution I thought for this was to calculate and store the accumulator with an increased precision of ONE_NXM and then scale back the value when calculating the amount of the rewards to transfer.

I applied that change in the commit [Increase accNxmPerRewardsShare precision](https://github.com/NexusMutual/smart-contracts/pull/529/commits/f930209d3ec98d6f45411d28e7aad26238a8d9e1)

Let me know your thoughts on this @shark0der

2023-01-03 09:26 UTC, shark0der commented
The `accNxmPerRewardsShare` fix looks good to me. In terms of semantics I think the previous value was:
> the accumulated nxm per **1 reward share**

where "1" was actually "1 wei"

The new value represents
> the accmuluated nxm per **1e18 reward shares**

which makes perfect sense and solves the precision loss issue.

2023-01-03 10:49 UTC, shark0der approved these changes

2023-01-03 10:51 UTC, shark0der requested changes
Right now it seems to me that all tests are using a single staker (unless I missed something). Could you please add a new test where 2+ stakers would deposit and withdraw their stake and rewards? I'm not expecting to discover any issues, but just in case, you know!

2023-01-04 10:05 UTC, roxdanila approved these changes

2023-01-05 13:27 UTC, shark0der approved these changes

2023-01-05 13:28 UTC, merged