Chore: Cleaning up proposal category constants
NexusMutual/smart-contracts pull request #630
Opened 2023-01-16 09:47 UTC by MilGard91

## Context

Proposal category constants not up to date and not being used in the tests

## Changes proposed in this pull request

Cleaning up proposal category constants so we don't use hardcoded codes

## Test plan

N/A

## Checklist

- [x] Rebased the base branch
- [ ] Attached corresponding Github issue
- [x] Prefixed the name with the type of change (i.e. feat, chore, test)
- [x] Performed a self-review of my own code
- [x] Followed the style guidelines of this project
- [ ] Made corresponding changes to the documentation
- [x] Didn't generate new warnings
- [x] Didn't generate failures on existing tests
- [ ] Added tests that prove my fix is effective or that my feature works

## Review

When reviewing a PR, please indicate intention in comments using the following emojis:
* :cake: = Nice to have but not essential.
* :bulb: = Suggestion or a comment based on personal opinion
* :hammer: = I believe this should be changed.
* :thinking: = I don’t understand something, do you mind giving me more context?
* :rocket: = Feedback

2023-01-16 10:43 UTC, roxdanila approved these changes

2023-01-16 10:43 UTC, roxdanila commented
🚢

2023-01-18 11:30 UTC, shark0der commented on lib/constants.js
> +  newContracts: 42, // mismatch from the https://app.nexusmutual.io/governance/categories
This needs to match the prod environment.

2023-01-18 11:30 UTC, shark0der commented on lib/constants.js
> +  setAddressDetails: 41,
Set **Asset** Details

2023-01-18 11:31 UTC, shark0der commented on lib/constants.js
> +  upgradeMasterAddress: 37,
Remove the `Address` suffix. This performs a master contract upgrade, the master contract address will not change since it's a proxy.

2023-01-18 11:33 UTC, shark0der commented on lib/constants.js
> +  editTokenControllerParameters: 35,
`updateTokenControllerParameters`

2023-01-18 11:34 UTC, shark0der commented on lib/constants.js
> +  editInvestmentAssetAddressDecimal: 32,
editInvestmentAssetAddress**And**Decimal

2023-01-18 11:37 UTC, shark0der commented on lib/constants.js
> +  changeVotingPeriodTo3Days: 18,
Please rename to `noAction`. No idea why the website says vote period here.

2023-01-18 11:39 UTC, shark0der commented on lib/constants.js
> +  editInvestmentAssetStatus: 15,
update*

2023-01-18 11:40 UTC, shark0der commented on lib/constants.js
> +  burnClaims: 8,
`burnClaimAssessor`

2023-01-18 11:43 UTC, shark0der commented on test/fork/migration-v2.js
> +      // TODO: change the categoryId when proposal is added
address after updating the list

2023-01-18 11:43 UTC, shark0der requested changes
See comments

2023-01-24 15:55 UTC, shark0der approved these changes

2023-01-24 16:06 UTC, merged