Block deposits and allocations when 100% of stake is burned
NexusMutual/smart-contracts pull request #633
Opened 2023-01-16 16:19 UTC by kyledewy

## Context
Closes #562 

## Changes proposed in this pull request

This PR adds a modifier to the staking pool, to block all deposits and cover buys on a staking pool if 100% of the active stake has been burned.
This is done to avoid division-by-zero issues.

## Test plan

A unit test was added at `StakingPool/burnStake.js`

## Checklist

- [ ] Rebased the base branch
- [ ] Attached corresponding Github issue
- [ ] Prefixed the name with the type of change (i.e. feat, chore, test)
- [ ] Performed a self-review of my own code
- [ ] Followed the style guidelines of this project
- [ ] Made corresponding changes to the documentation
- [ ] Didn't generate new warnings
- [ ] Didn't generate failures on existing tests
- [ ] Added tests that prove my fix is effective or that my feature works

## Review

When reviewing a PR, please indicate intention in comments using the following emojis:
* :cake: = Nice to have but not essential.
* :bulb: = Suggestion or a comment based on personal opinion
* :hammer: = I believe this should be changed.
* :thinking: = I don’t understand something, do you mind giving me more context?
* :rocket: = Feedback

2023-01-20 18:39 UTC, shark0der commented on contracts/modules/staking/StakingPool.sol
> +    require(!insolvent, "StakingPool: All coverage has been claimed. Must create new pool");
Rebase and use custom error please :pray:
@roxdanila unsure about the terminology used here, might be worth a short brainstorming session to see what would be a better wording.

2023-01-20 18:40 UTC, shark0der commented on contracts/mocks/TokenControllerMock.sol
> +    token().burn(amount);
Remove the comment

2023-01-20 18:43 UTC, shark0der commented on contracts/modules/staking/StakingPool.sol
> +    activeStake = _activeStake - amount;
Leave a todo to so we'll add a burn event.

2023-01-20 18:44 UTC, shark0der requested changes
see comments

2023-01-25 17:04 UTC, kyledewy commented on contracts/modules/staking/StakingPool.sol
> +  ) external onlyCoverContract whenNotHalted returns (uint premium, uint allocationId) {
remove `whenNotHalted` check from `requestAllocation`

2023-01-27 14:11 UTC, roxdanila commented
@kyledewy one conflict and a failed test to look at

2023-01-30 12:49 UTC, shark0der approved these changes

2023-01-30 13:31 UTC, roxdanila approved these changes

2023-01-30 13:31 UTC, merged