add fix for effectiveWeight issue
NexusMutual/smart-contracts pull request #831
Opened 2023-03-27 04:15 UTC by danoctavian

## Context

Include relevant motivation and context. A link to the issue is enough if it contains all the relevant 
information.

## Changes proposed in this pull request

Include a summary of the change.

## Test plan

Please describe the tests cases that you ran to verify your changes. Add further instructions on 
how to run them if needed (i.e. migration / deployment scripts, env vars, etc).

## Checklist

- [ ] Rebased the base branch
- [ ] Attached corresponding Github issue
- [ ] Prefixed the name with the type of change (i.e. feat, chore, test)
- [ ] Performed a self-review of my own code
- [ ] Followed the style guidelines of this project
- [ ] Made corresponding changes to the documentation
- [ ] Didn't generate new warnings
- [ ] Didn't generate failures on existing tests
- [ ] Added tests that prove my fix is effective or that my feature works

## Review

When reviewing a PR, please indicate intention in comments using the following emojis:
* :cake: = Nice to have but not essential.
* :bulb: = Suggestion or a comment based on personal opinion
* :hammer: = I believe this should be changed.
* :thinking: = I don’t understand something, do you mind giving me more context?
* :rocket: = Feedback

2023-03-27 06:02 UTC, danoctavian commented on contracts/modules/staking/StakingPool.sol
> +    uint productTargetWeight
reason for doing this:

Couldn't find a way to reliably reverse the calculation in StakingProducts in the case that productTargetWeight is set to 0 (information loss).

We could still expose the same function (exact same interface) without this parameter and have an internal _ getTrancheCapacities that has the parameter and is used by all other ones.

I didn't see getTrancheCapacities used anywhere yet though so i modified it directly.

2023-03-27 06:04 UTC, danoctavian commented on test/integration/StakingProducts/recalculateEffectiveWeightsForAllProducts.js
> +      // Cover inputs for cover purchase used to increase activeWeight
could refactor this block into a function, i duplicated it for now

2023-03-27 09:01 UTC, MilGard91 reviewed
Apart for the ids, lgtm

2023-03-27 09:03 UTC, danoctavian commented on test/fork/recalculate-effective-weights-bug-fix.js
> +      await stakingProducts.recalculateEffectiveWeightsForAllProducts(i);
thanks good point

2023-03-27 09:58 UTC, MilGard91 approved these changes

2023-03-27 10:39 UTC, danoctavian commented on test/fork/recalculate-effective-weights-bug-fix.js
> +const { ethers } = require('hardhat');
i made a separate file from @kyledewy  to just test this particular upgrade but reused his verification logic.

Happy to adjust if you think there should just be 1.

2023-04-07 11:58 UTC, roxdanila requested changes
I think we can find a cleaner solution, this is a bit messy imo

2023-04-10 21:42 UTC, danoctavian commented on contracts/modules/staking/StakingProducts.sol
> +    uint activeStake = stakingPool.getActiveStake();
fix implemented as @shark0der  proposed.

2023-05-04 10:08 UTC, shark0der approved these changes

2023-05-04 12:29 UTC, roxdanila approved these changes
🚢

2023-05-04 12:29 UTC, merged